### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Telegram-Notifly#3]

**Comment by Godspower-Eze** [comment]
I could do this. Assign this to me

**Comment by rexdivakar** [comment]
Hey @Godspower-Eze  sorry but it's an internal work anyways thanks for ur interest.

**Comment by Tawishi** [comment]
@rexdivakar I would like to work on this.

**Comment by rexdivakar** [comment]
Great job💯  @Tawishi  Highly appreciated  👍

**Comment by Tawishi** [comment]
> Great job💯 @Tawishi Highly appreciated 👍

Thank you for the acknowledgement.
Really appreciate the trust you showed in my work.
