### ISSUE TITLE
Files Downloader 

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Telegram-Notifly#8]
Objective is to download the files sent to the telegram chat onto our local folder.

**Comment by chmey** [comment]
I'll do it!

**Comment by rexdivakar** [comment]
Great, keep in mind to create a new folder if it doesn't exist and then download the files that are sent by the user on telegram.

Issue assigned to @chmey 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/e47wmTW

**Comment by chmey** [comment]
@rexdivakar The PR is ready at your hands: #18
